### registro de usuario

POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "prueba5",
    "email":"casa14@gmail.com",
    "password": "123456",
    "telefono": "hola"
}


### Login sin conexion a base de datos

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "prueba5",
    "email":"casa14@gmail.com",
    "password": "123456",
    "telefono": "hola"
}


### 
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhc2ExNEBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzE4NTkzOTQ2LCJleHAiOjE3MTg1OTQ1NTF9.Z0lms3m2fJ9A0Uk4aLZomfUwn8KaIK6am-0qIhJMDec
#####
GET http://127.0.0.1:3000/categoria

