## Login sin conexion a base de datos

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "prueba2",
    "email":"casa2@gmail.com",
    "password": "654321"
}



POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "prueba",
    "email":"casa@gmail.com",
    "password": "123456"
}



